
Character.create({name: "The Kidnapped Child"})
Character.create({name: "Halfdan Ragnorsson"})
Character.create({name: "Loki"})
Character.create({name: "Emory"})
Character.create({name: "Kat"})
Character.create({name: "War"})
Character.create({name: "Bart"})
Character.create({name: "Johannas"})
Character.create({name: "Dr. Yuri Krolm"})
Character.create({name: "Lavender the Pixie"})
Character.create({name: "The Gentle Grandmother"})
Character.create({name: "The Storyteller"})
Character.create({name: "Ali"})
Character.create({name: "Oriana"})
