puts "===> Changelings"
Character.create({name: "Adi Kapur", species: "Changeling"})
Character.create({name: "Issac Corvi", species: "Changeling"})
Character.create({name: "Molly Severson", species: "Changeling"})

puts "===> True Fae"
puts "===> Hobs"

Character.create({name: "Jillian Bordeaux"})
Character.create({name: "Charles Harding"})
Character.create({name: "The Kidnapped Child"})
Character.create({name: "Aldric Durant"})
Character.create({name: "Persephone Floros"})
Character.create({name: "Chikiri Komieji"})
Character.create({name: "Halfdan Ragnorsson"})
Character.create({name: "Lumi Satala"})
Character.create({name: "Aravinda"})
Character.create({name: "Loki"})
Character.create({name: "Gon"})
Character.create({name: "Emory"})
Character.create({name: "The Winter Monarch"})
Character.create({name: "The Emerald Queen"})
Character.create({name: "The Summer King"})
Character.create({name: "The Jester"})
Character.create({name: "Kat"})
Character.create({name: "War"})
Character.create({name: "Vellum the Studious"})
Character.create({name: "Bart"})
Character.create({name: "Johannas"})
Character.create({name: "Satori Komieji"})
Character.create({name: "Valtor Alton"})
Character.create({name: "Matthew Satorius"})
Character.create({name: "Dr. Yuri Krolm"})
Character.create({name: "The Zookeeper"})
Character.create({name: "Lavender the Pixie"})
Character.create({name: "Neithan"})
Character.create({name: "The Problem Solver"})
Character.create({name: "The Gentle Grandmother"})
Character.create({name: "The Storyteller"})
Character.create({name: "The Game Maker"})
Character.create({name: "The False Deity"})
Character.create({name: "Ali"})
Character.create({name: "Oriana"})
Character.create({name: "Francis Ayers"})
Character.create({name: "Fredrick Ackerley"})
Character.create({name: "Elizabeth Ward"})
